/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    MultiApplyCard: typeof import('./src/components/MultiApplyCard.vue')['default']
    OutsideJops: typeof import('./src/components/outsideJops.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    RecomJops: typeof import('./src/components/recomJops.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
  }
}
